# Generated by Django 5.0 on 2023-12-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawApp', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Rather not say')], default='nonbinary', max_length=30),
        ),
    ]
