# Generated by Django 5.0.1 on 2024-01-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RawApp', '0006_delete_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
