# Generated by Django 5.0.1 on 2024-01-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RawApp', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
