# Generated by Django 5.0.1 on 2024-01-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RawApp', '0010_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
